/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInterviewRouteImport } from './routes/api/interview'
import { Route as ApiPortfolioRouteImport } from './routes/api/portfolio'
import { Route as ApiPresenceRouteImport } from './routes/api/presence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewRoute = ApiInterviewRouteImport.update({
  id: '/api/interview',
  path: '/api/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioRoute = ApiPortfolioRouteImport.update({
  id: '/api/portfolio',
  path: '/api/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresenceRoute = ApiPresenceRouteImport.update({
  id: '/api/presence',
  path: '/api/presence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/portfolio': typeof ApiPortfolioRoute
  '/api/presence': typeof ApiPresenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/portfolio': typeof ApiPortfolioRoute
  '/api/presence': typeof ApiPresenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/portfolio': typeof ApiPortfolioRoute
  '/api/presence': typeof ApiPresenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/interview' | '/api/portfolio' | '/api/presence'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/interview' | '/api/portfolio' | '/api/presence'
  id: '__root__' | '/' | '/api/interview' | '/api/portfolio' | '/api/presence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiInterviewRoute: typeof ApiInterviewRoute
  ApiPortfolioRoute: typeof ApiPortfolioRoute
  ApiPresenceRoute: typeof ApiPresenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview': {
      id: '/api/interview'
      path: '/api/interview'
      fullPath: '/api/interview'
      preLoaderRoute: typeof ApiInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio': {
      id: '/api/portfolio'
      path: '/api/portfolio'
      fullPath: '/api/portfolio'
      preLoaderRoute: typeof ApiPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presence': {
      id: '/api/presence'
      path: '/api/presence'
      fullPath: '/api/presence'
      preLoaderRoute: typeof ApiPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiInterviewRoute: ApiInterviewRoute,
  ApiPortfolioRoute: ApiPortfolioRoute,
  ApiPresenceRoute: ApiPresenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
